api_platform:
  title: "France Driver REST API"
  description: "A API for Admin"
  version: "1.0.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
